name: anywhere_code_exercise
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SimpsonsFont
      fonts:
        - asset: assets/app_fonts/Simpsonfont.ttf
    - family: WireFont
      fonts:
        - asset: assets/app_fonts/BohemianTypewriter.ttf
